-- Create storage bucket for exam papers (run in Supabase SQL editor if not created via Storage UI)
-- select storage.create_bucket('exam-papers', public := true);

-- Create table to store exam files metadata
create table if not exists public.exam_files (
  id bigint generated by default as identity primary key,
  title text not null,
  file_name text not null,
  file_path text not null,
  file_type text not null,
  file_size bigint not null,
  public_url text not null,
  topic_id integer null references public.topics(id) on delete set null,
  uploaded_by uuid null,
  created_at timestamp with time zone not null default now()
);

-- Enable RLS
alter table public.exam_files enable row level security;

-- Policies: allow read for everyone (client runs as anon/authenticated)
drop policy if exists "exam_files_select_public" on public.exam_files;
create policy "exam_files_select_public"
  on public.exam_files for select
  to anon, authenticated
  using (true);

-- Allow insert/update/delete for authenticated users only (teachers)
drop policy if exists "exam_files_insert_auth" on public.exam_files;
create policy "exam_files_insert_auth"
  on public.exam_files for insert
  to authenticated
  with check (true);

drop policy if exists "exam_files_update_auth" on public.exam_files;
create policy "exam_files_update_auth"
  on public.exam_files for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "exam_files_delete_auth" on public.exam_files;
create policy "exam_files_delete_auth"
  on public.exam_files for delete
  to authenticated
  using (true);

-- Helpful index
create index if not exists exam_files_created_at_idx on public.exam_files(created_at desc);

-- Storage policies (public read already usually exists via dashboard settings)
-- Allow anon to delete objects in 'exam-papers' (for demo). For production, restrict to authenticated.
drop policy if exists "exam_papers_anon_delete" on storage.objects;
create policy "exam_papers_anon_delete"
on storage.objects for delete
to anon
using (bucket_id = 'exam-papers');

-- Allow anon to read objects in 'exam-papers'
drop policy if exists "exam_papers_public_read" on storage.objects;
create policy "exam_papers_public_read"
on storage.objects for select
to public
using (bucket_id = 'exam-papers');

-- Table delete policy (for demo; for production, prefer authenticated only)
drop policy if exists "exam_files_delete_public" on public.exam_files;
create policy "exam_files_delete_public"
  on public.exam_files for delete
  to anon, authenticated
  using (true);

